### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MFarelS** [hisyamardiansyah/Tulisno#3]
Tutor custom lokasi text stah

**Comment by MFarelS** [comment]
Jadi saya mau atur lokasi tulisannya, itu gimana om?

**Comment by MFarelS** [comment]
Gimana bang😭😥

**Comment by hisyamardiansyah** [comment]
Di bagian function draw,  text(txtContent, 0, 0, 580 /*, 800 */ ) sesuaikan kordinat nya sesuai costum sendiri

**Comment by MFarelS** [comment]
> Di bagian function draw, text(txtContent, 0, 0, 580 /*, 800 */ ) sesuaikan kordinat nya sesuai costum sendiri

Nentuin pake Mspaint bisa kah?

**Comment by MFarelS** [comment]
Belom terjawab 😂

**Comment by MFarelS** [comment]
> Hadeh dah pinter coding ngapain tanya segala pake Mspaint? Mspaint software buat gambar pak

Lah, kan bot nulis w atur kordinatnya pake Mspaint 😂
Awokwaokwaok
